logs:
    - name: root
      level: info
      appenders:
          - type: FileLogAppender
            file: /home/wxb/computerprograms/c++/sylar-wxb/logs/root.txt
          - type: StdoutLogAppender
    - name: system
      level: info
      appenders:
          - type: FileLogAppender
            file: /home/wxb/computerprograms/c++/sylar-wxb/logs/system.txt
          - type: StdoutLogAppender
